### PR TITLE
Consolidate figure and media patterns.

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
 - Consolidates __Media__ pattern into the new and improved __Figure__ pattern.

For review: @DoSomething/front-end 

# Screenshot
screen shot 2015-02-11 at 11 45 30 am

### CODE REVIEW

**Comment by sbsmith86** [comment]
Do we need to update the meda.tpl.php?

**Comment by DFurnes** [comment]
Yup, we'll need to combine those two templates and probably update the theme functions a little bit once this gets released.

**Comment by sbsmith86** [comment]
cool :+1:

**Comment by weerd** [comment]
Still kinda prefer the more "general-ness" of `media` but `figure` is a bit more user friendly :\ Just some Diego $0.02.

:+1:

**Comment by DFurnes** [comment]
Merging! Let's keep mulling over naming for this pattern until release.

**Pull request merged**
