### PR TITLE
Removed left margin on secondary navigation anchor

### PR DESCRIPTION
**Pull request by deadlybutter**
Fixes the spacing issue, needed for https://github.com/DoSomething/dosomething/issues/1861

Before:
screen shot 2015-01-14 at 2 58 02 pm

After:
screen shot 2015-01-14 at 2 57 57 pm

### CODE REVIEW

**Comment by DFurnes** [comment]
This doesn't leave much spacing between the search field and navigation links. Can someone on the @DoSomething/design team weigh in?

**Comment by lkpttn** [comment]
Is there a place that I can see this on either my machine or a devs?

**Comment by deadlybutter** [comment]
I'm not in but its easy to replicate, Right click 'Register' --> Inspect element --> uncheck/check marginleft like in the screenshots above

**Comment by lkpttn** [comment]
Commenting with what was put in hipchat:

The :after selector needs to have a right: -12px instead of 0px
and 12px left/right space on the search bar to balance it out.

**Comment by deadlybutter** [comment]
@lkpttn hmm, if you were working from the code I already did all ya needed to do was give the search bar a right margin

@DFurnes alright this should be good now 

screen shot 2015-01-20 at 3 01 14 pm

**Comment by DFurnes** [comment]
That still causes the two navigation items to be really closely spaced together. Ideally, we'd want all the navigation items to more even spacing.

**Comment by deadlybutter** [comment]
new PR coming soon to replace this + add many other nav changes

**Comment by lkpttn** [comment]
@deadlybutter Has the new PR been submitted?

**Comment by mikefantini** [comment]
PR would be relating to https://github.com/DoSomething/dosomething/issues/1861

**Comment by deadlybutter** [comment]
@lkpttn my neue ran into a ton of problems and @DFurnes had to help me fix it, unfortunatley I had to recode most of it. after I get the JS is tested it should be good to go

**Pull request closed without merging**
