### PR TITLE
Fix gutter on heading banner on mobile.

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
 - Fixes gutter on heading banner on mobile.

For review: @DoSomething/front-end 

# Screenshots

#### Not ideal:
screen shot 2015-01-23 at 1 15 48 pm

#### Just perfect:
screen shot 2015-01-23 at 1 15 36 pm

### CODE REVIEW

**Comment by weerd** [comment]
Would `line-height: 1;` help vertically center?

**Comment by weerd** [comment]
Sorry. clicked the wrong button. Didn't mean to close!

**Comment by DFurnes** [comment]
Damn it Diego! :rage1:

**Comment by DFurnes** [comment]
Re: `line-height`, I don't think so. It seems to be an issue with Proxima Nova. Line-height doesn't change anything, but switching over to Helvetica makes it look better. :unamused:

**Comment by weerd** [comment]
Dang. ok! :+1:

**Pull request merged**
