### PR TITLE
Slanted Container (experimental)

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
 - Playing around with new modifier for the Container pattern, based on some lovely mocks from the design team. Posted to save for later, and for feedback/discussion.

__Not ready for merge.__ :rotating_light: 

# Screenshots
screen shot 2015-03-27 at 4 00 42 pm

And on a content page...
screen shot 2015-03-27 at 4 00 34 pm

### CODE REVIEW

**Comment by DFurnes** [comment]
And experimenting with some bolder colors in the Web Inspector. Perhaps a `.-loud` modifier.

screen shot 2015-03-27 at 4 12 39 pm

**Comment by sbsmith86** [comment]
I like that!

**Comment by julielorch** [comment]
PURPLE AND YELLOW IN THE MOCKS

**Comment by DFurnes** [comment]
Rebased against latest dev, and added "loud" container modifier in code. Also made an experimental version of the Header's "banner" modifier based on Action Page mock.

**Comment by DFurnes** [comment]
Another screenshot:

screen shot 2015-04-06 at 4 50 23 pm

**Comment by DFurnes** [comment]
And with the Prove It section:

screen shot 2015-04-06 at 4 53 38 pm

**Comment by DFurnes** [comment]
:skull:

**Pull request closed without merging**
