### PR TITLE
Move SVG icons into data URLs.

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
 - Moves remaining SVG icons (search, loading spinner) into data URLs. This means less HTTP requests and faster page-loads (at least until HTTP/2 arrives!)
 - Changes option icons (checkmark and radio button) from base64-encoded data URLs to UTF-8. This is easier to edit (yay!) and gzips better when packing a bunch of icons into the CSS source (extra yay!)
 - Adds a nice little `data-url()` helper function.

For review: @DoSomething/front-end

### CODE REVIEW

**Comment by barryclark** [comment]
Nice!

**Comment by weerd** [comment]
Pretty cool! Can you confirm these load fine in IE9/10 + Firefox?

**Comment by DFurnes** [comment]
:sob:

**Comment by DFurnes** [comment]
Alright! Fixed. :godmode: 

We needed to URL-encode data URLs for these to work properly in IE9, IE10, and Firefox. Hacked together a little `url-encode()` function which was pretty cool though so not all is lost.

**Comment by weerd** [comment]
@_@ :+1: cool stuff!

**Pull request merged**
